# This is a config for E2B sandbox template.
# You can use template ID (beav13njbfo1c0j75kg2) or template name (void-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("void-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("void-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('void-nextjs')

team_id = "bd90d715-8b0e-4812-a34c-cb4544abe25c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "void-nextjs"
template_id = "beav13njbfo1c0j75kg2"
